### ISSUE TITLE
Header error text at the "1. Cluster setup" section 

### ISSUE THREAD

**Issue by dkholodo** [openshift-metalkube/facet#45]
Steps to reproduce:
1. Just open the Facet initial page

Expected result:
There should be no any errors at the header

Actual result:
{ "error": null } at the header (please see the screenshot)
![Header error text at the  1  Cluster setup  section ](https://user-images.githubusercontent.com/37401605/54125856-d547e380-440e-11e9-80bf-6a4536abc4e5.jpg)

**Comment by jtomasek** [comment]
FIx merged, closing
